### ISSUE TITLE
I was promised useful actions

### ISSUE THREAD

**Issue by gitblit** [vas-dev/vas-actions#1]
## Background

I've clearly been promised useful actions.

![image](https://user-images.githubusercontent.com/868217/53049872-05cadc00-3466-11e9-9222-222688fedb23.png)

## Problem

Need more useful.

**Comment by MarceloAlves** [comment]
Keyword:
>semi-useful

😄

**Comment by gitblit** [comment]
Do you think this repo should be public?

**Comment by MarceloAlves** [comment]
Action repos have to be public in order to be used unfortunately. The current action and hopefully future actions don't leak anything private. Goal is to use it for linters and such

**Comment by gitblit** [comment]
Ok, thanks for the info. That's an unfortunate handicap.  We'll have to be careful about how we use Actions until GitHub gets smarter.
